# Fabric Properties
minecraft_version=26.3

# Fabric Mod Metadata
carpet_dependency=>=26.3-
minecraft_dependency=>=26.3
skinrestorer_dependency=>=2.7.1

# Build Information
game_versions=26.3

# Mod Dependency
carpet_core_version=26.3+v260915

# Dependencies
fabric_api_version=0.161.0+26.3
skinrestorer_name=_disabled_skinrestorer
